// Phase 1 coverage expansion: fills zero/low-coverage taxonomy areas.
// Keep these questions Balanced until they receive hard-mode review.

const PHYSICIAN_TASK = 'Medical Knowledge: Applying Foundational Science Concepts'

function q({
  id,
  subject,
  system,
  concept,
  topic,
  contentArea,
  subdomain,
  angle,
  stem,
  correct,
  distractors,
  explanation,
  pearl,
  trap,
}) {
  return {
    id,
    subject,
    system,
    difficulty: 'Balanced',
    testedConcept: concept,
    weakSpotCategory: topic,
    usmleContentArea: contentArea,
    usmleSubdomain: subdomain || topic,
    physicianTask: PHYSICIAN_TASK,
    topic,
    questionAngle: angle,
    memoryAnchor: pearl,
    commonTrap: trap,
    stem,
    options: [
      { letter: 'A', text: correct },
      { letter: 'B', text: distractors[0] },
      { letter: 'C', text: distractors[1] },
      { letter: 'D', text: distractors[2] },
    ],
    correct: 'A',
    explanation,
    pearl,
  }
}

export const COVERAGE_EXPANSION_QUESTIONS = [
  q({
    id: 'qCOVGEN001',
    subject: 'Genetics',
    system: 'Oncology',
    concept: 'Knudson two-hit hypothesis for retinoblastoma tumor suppression',
    topic: 'Tumor Suppressor Genetics',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'genetics',
    stem: 'A 2-year-old boy has leukocoria and is found to have bilateral retinal tumors. Genetic testing shows one inherited RB1 pathogenic variant and loss of the remaining normal allele in tumor cells. Which mechanism best explains the development of his tumors?',
    correct: 'Loss of both tumor suppressor alleles',
    distractors: ['Activation of one proto-oncogene allele', 'Expansion of a trinucleotide repeat', 'Mitochondrial heteroplasmy'],
    explanation: 'The best answer is loss of both tumor suppressor alleles because RB1 follows the Knudson two-hit model: an inherited first hit plus somatic loss of the second allele permits retinal tumor formation.',
    pearl: 'Tumor suppressor genes usually require loss of both alleles; oncogenes usually require activation of one allele.',
    trap: 'Proto-oncogene activation is a gain-of-function mechanism and does not explain inherited bilateral retinoblastoma.',
  }),
  q({
    id: 'qCOVGEN002',
    subject: 'Genetics',
    system: 'Neurology',
    concept: 'Anticipation from trinucleotide repeat expansion in Huntington disease',
    topic: 'Trinucleotide Repeat Disorders',
    contentArea: 'Nervous System & Special Senses',
    angle: 'genetics',
    stem: 'A 32-year-old man develops choreiform movements and personality changes. His father had similar symptoms beginning at age 48. Genetic testing shows an expanded CAG repeat. Which genetic principle explains the earlier onset in this patient?',
    correct: 'Anticipation due to repeat expansion',
    distractors: ['Genomic imprinting from maternal silencing', 'Loss of heterozygosity in neurons', 'Nondisjunction during meiosis I'],
    explanation: 'The best answer is anticipation due to repeat expansion because Huntington disease can show worsening severity or earlier onset in successive generations as CAG repeats expand.',
    pearl: 'CAG repeat expansion in Huntington disease encodes an expanded polyglutamine tract.',
    trap: 'Nondisjunction changes chromosome number, not repeat length.',
  }),
  q({
    id: 'qCOVGEN003',
    subject: 'Genetics',
    system: 'Hematology',
    concept: 'Autosomal recessive inheritance risk in sickle cell disease',
    topic: 'Mendelian Inheritance',
    contentArea: 'Blood & Lymphoreticular System',
    angle: 'genetics',
    stem: 'Two healthy parents each have one child with sickle cell disease. They ask about the risk that their next child will also be affected. Which inheritance pattern and recurrence risk are most consistent with this disorder?',
    correct: 'Autosomal recessive inheritance with a 25% affected risk',
    distractors: ['Autosomal dominant inheritance with a 50% affected risk', 'X-linked recessive inheritance with affected sons only', 'Mitochondrial inheritance with all children affected'],
    explanation: 'The best answer is autosomal recessive inheritance with a 25% affected risk because two carrier parents have a one-in-four chance of having an affected child in each pregnancy.',
    pearl: 'For two carriers of an autosomal recessive disease: 25% affected, 50% carrier, 25% unaffected noncarrier.',
    trap: 'Carrier parents are typically clinically well, so the pattern can be missed if only symptoms are considered.',
  }),
  q({
    id: 'qCOVGEN004',
    subject: 'Genetics',
    system: 'Reproductive',
    concept: 'Nondisjunction causing trisomy 21',
    topic: 'Chromosomal Nondisjunction',
    contentArea: 'Human Development',
    angle: 'genetics',
    stem: 'A newborn has hypotonia, a single palmar crease, upslanting palpebral fissures, and a complete atrioventricular canal defect. Karyotype shows 47,XY,+21. Which meiotic error most commonly causes this condition?',
    correct: 'Maternal meiotic nondisjunction',
    distractors: ['Paternal mitochondrial mutation', 'Balanced reciprocal translocation only', 'Somatic loss of a tumor suppressor allele'],
    explanation: 'The best answer is maternal meiotic nondisjunction because most cases of trisomy 21 result from failure of chromosome 21 separation during maternal meiosis.',
    pearl: 'Trisomy 21 risk increases with maternal age due to meiotic nondisjunction.',
    trap: 'Robertsonian translocation can cause Down syndrome, but nondisjunction is the most common mechanism.',
  }),
  q({
    id: 'qCOVGEN005',
    subject: 'Genetics',
    system: 'Endocrine',
    concept: 'MEN2 RET proto-oncogene gain of function',
    topic: 'Endocrine Cancer Genetics',
    contentArea: 'Endocrine System',
    angle: 'genetics',
    stem: 'A teenager with a family history of medullary thyroid carcinoma undergoes genetic testing and is found to have a RET mutation. Relatives with the same mutation are advised to consider prophylactic thyroidectomy. What type of genetic alteration drives this syndrome?',
    correct: 'Gain-of-function mutation in a proto-oncogene',
    distractors: ['Loss-of-function mutation in a DNA repair gene', 'Deletion of both tumor suppressor alleles', 'Expansion of a noncoding trinucleotide repeat'],
    explanation: 'The best answer is gain-of-function mutation in a proto-oncogene because MEN2 is caused by activating RET mutations that increase growth signaling.',
    pearl: 'RET activation is associated with MEN2A and MEN2B; medullary thyroid carcinoma is the key risk.',
    trap: 'Tumor suppressor loss usually requires two hits, but RET behaves as an activated oncogene.',
  }),
  q({
    id: 'qCOVGEN006',
    subject: 'Genetics',
    system: 'Renal / Urinary',
    concept: 'X-linked dominant inheritance in Alport syndrome',
    topic: 'Collagen Genetics',
    contentArea: 'Renal & Urinary System',
    angle: 'genetics',
    stem: 'A boy has recurrent hematuria, progressive sensorineural hearing loss, and ocular abnormalities. Several male relatives on his mother\'s side developed renal failure at a young age. Which inheritance pattern best fits the most common form of this disease?',
    correct: 'X-linked dominant inheritance',
    distractors: ['Autosomal recessive inheritance only', 'Mitochondrial inheritance', 'Y-linked inheritance'],
    explanation: 'The best answer is X-linked dominant inheritance because the most common form of Alport syndrome involves COL4A5 and causes hematuria, hearing loss, and ocular findings.',
    pearl: 'Alport syndrome affects type IV collagen in glomerular basement membrane, cochlea, and eye.',
    trap: 'Male-to-male transmission is absent in X-linked disease.',
  }),
  q({
    id: 'qCOVGEN007',
    subject: 'Genetics',
    system: 'Gastrointestinal',
    concept: 'APC loss initiating familial adenomatous polyposis',
    topic: 'Colon Cancer Genetics',
    contentArea: 'Gastrointestinal System',
    angle: 'genetics',
    stem: 'A 16-year-old girl undergoes colonoscopy because of a parent with colon cancer at age 35. Hundreds of adenomatous polyps are found throughout the colon. Mutation of which type of gene is most likely responsible for the initiating event?',
    correct: 'Tumor suppressor gene regulating beta-catenin',
    distractors: ['Proto-oncogene encoding a tyrosine kinase receptor', 'Mismatch repair gene causing microsatellite instability only', 'Mitochondrial gene encoding oxidative phosphorylation protein'],
    explanation: 'The best answer is tumor suppressor gene regulating beta-catenin because APC loss initiates familial adenomatous polyposis and promotes Wnt pathway activation.',
    pearl: 'APC loss is an early event in the adenoma-carcinoma sequence.',
    trap: 'Mismatch repair defects cause Lynch syndrome, which usually has few polyps compared with FAP.',
  }),
  q({
    id: 'qCOVGEN008',
    subject: 'Genetics',
    system: 'Respiratory',
    concept: 'CFTR delta F508 protein misfolding',
    topic: 'Cystic Fibrosis Genetics',
    contentArea: 'Respiratory System',
    angle: 'genetics',
    stem: 'A child has recurrent sinopulmonary infections, pancreatic insufficiency, and elevated sweat chloride. Genetic testing shows deletion of phenylalanine at position 508 of CFTR. What is the main effect of this mutation?',
    correct: 'Misfolding with defective trafficking of a chloride channel',
    distractors: ['Excess transcription of a sodium channel', 'Defective collagen cross-linking', 'Failure of lysosomal enzyme phosphorylation'],
    explanation: 'The best answer is misfolding with defective trafficking of a chloride channel because delta F508 CFTR is degraded before reaching the apical membrane.',
    pearl: 'Cystic fibrosis causes thick secretions due to defective chloride transport and increased sodium absorption.',
    trap: 'The mutation does not primarily increase sodium channel transcription.',
  }),
  q({
    id: 'qCOVGEN009',
    subject: 'Genetics',
    system: 'Musculoskeletal',
    concept: 'FBN1 mutation causing Marfan syndrome',
    topic: 'Connective Tissue Genetics',
    contentArea: 'Musculoskeletal System',
    angle: 'genetics',
    stem: 'A tall adolescent has long fingers, pectus excavatum, lens subluxation, and dilation of the aortic root. His father had similar findings. Mutation of which extracellular matrix protein best explains the syndrome?',
    correct: 'Fibrillin-1',
    distractors: ['Type I collagen', 'Dystrophin', 'Elastase'],
    explanation: 'The best answer is fibrillin-1 because Marfan syndrome is caused by FBN1 mutations that impair microfibrils and increase TGF-beta signaling.',
    pearl: 'Marfan syndrome: tall habitus, lens subluxation, and aortic root dilation.',
    trap: 'Type I collagen defects cause osteogenesis imperfecta, not the classic Marfan pattern.',
  }),
  q({
    id: 'qCOVGEN010',
    subject: 'Genetics',
    system: 'Multisystem',
    concept: 'Mitochondrial inheritance from maternal transmission',
    topic: 'Mitochondrial Genetics',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'genetics',
    stem: 'Several siblings have exercise intolerance, lactic acidosis, and neurologic symptoms. Their mother has mild similar symptoms, but their father is unaffected. Which inheritance pattern best explains this family history?',
    correct: 'Maternal mitochondrial inheritance',
    distractors: ['Autosomal dominant inheritance with paternal transmission', 'Y-linked inheritance', 'Autosomal recessive inheritance with carrier parents'],
    explanation: 'The best answer is maternal mitochondrial inheritance because mitochondria are transmitted through the oocyte, so affected mothers can pass disease to children of any sex.',
    pearl: 'Mitochondrial disease severity varies because of heteroplasmy.',
    trap: 'Affected fathers do not transmit mitochondrial DNA to offspring.',
  }),

  q({
    id: 'qCOVBEH001',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Major depressive disorder diagnostic duration',
    topic: 'Mood Disorders',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'A 29-year-old woman reports depressed mood, anhedonia, insomnia, low energy, impaired concentration, and guilt for the past 6 weeks. She denies manic episodes and substance use. Which diagnosis best explains these symptoms?',
    correct: 'Major depressive disorder',
    distractors: ['Persistent depressive disorder', 'Cyclothymic disorder', 'Normal bereavement without functional impairment'],
    explanation: 'The best answer is major depressive disorder because at least 5 depressive symptoms including depressed mood or anhedonia for at least 2 weeks cause impairment.',
    pearl: 'Major depressive disorder requires a minimum 2-week episode and exclusion of mania or hypomania.',
    trap: 'Persistent depressive disorder requires chronic depressed mood for at least 2 years.',
  }),
  q({
    id: 'qCOVBEH002',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Panic disorder with unexpected panic attacks',
    topic: 'Anxiety Disorders',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'A 24-year-old student has recurrent sudden episodes of palpitations, trembling, dyspnea, chest tightness, and fear of dying. The episodes peak within 10 minutes and are followed by persistent worry about another attack. Which diagnosis is most likely?',
    correct: 'Panic disorder',
    distractors: ['Generalized anxiety disorder', 'Illness anxiety disorder', 'Obsessive-compulsive disorder'],
    explanation: 'The best answer is panic disorder because recurrent unexpected panic attacks followed by concern or behavioral change define the disorder.',
    pearl: 'Panic attacks peak rapidly and include autonomic symptoms plus intense fear.',
    trap: 'Generalized anxiety disorder is chronic excessive worry, not discrete abrupt attacks.',
  }),
  q({
    id: 'qCOVBEH003',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Obsessive-compulsive disorder ego-dystonic obsessions',
    topic: 'Obsessive-Compulsive Disorders',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'A 31-year-old man spends hours checking that the stove is off despite knowing the behavior is excessive. He feels intense anxiety if he resists checking. Which feature best characterizes his intrusive thoughts?',
    correct: 'Ego-dystonic obsessions relieved temporarily by compulsions',
    distractors: ['Fixed false beliefs without insight', 'Flashbacks after traumatic exposure', 'Voluntary habits performed for pleasure'],
    explanation: 'The best answer is ego-dystonic obsessions relieved temporarily by compulsions because OCD involves unwanted intrusive thoughts and repetitive behaviors that reduce anxiety.',
    pearl: 'OCD obsessions are intrusive and unwanted; compulsions are performed to neutralize distress.',
    trap: 'Delusions are fixed false beliefs and are not typically recognized as excessive.',
  }),
  q({
    id: 'qCOVBEH004',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Classical conditioning in anticipatory nausea',
    topic: 'Learning Theory',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'A patient receiving chemotherapy begins to feel nauseated when entering the infusion clinic, before any medication is administered. The clinic environment has repeatedly been paired with nausea from prior treatments. Which learning mechanism explains this response?',
    correct: 'Classical conditioning',
    distractors: ['Operant conditioning by positive reinforcement', 'Observational learning', 'Extinction burst'],
    explanation: 'The best answer is classical conditioning because a neutral stimulus becomes associated with an unconditioned nausea response after repeated pairing.',
    pearl: 'Classical conditioning links stimuli; operant conditioning links behavior and consequences.',
    trap: 'Positive reinforcement increases a behavior after a rewarding consequence.',
  }),
  q({
    id: 'qCOVBEH005',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Precontemplation stage of change',
    topic: 'Motivational Interviewing',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'A 52-year-old man with COPD continues smoking and says, "Smoking is not a problem for me, and I am not interested in quitting." Which stage of behavioral change is he demonstrating?',
    correct: 'Precontemplation',
    distractors: ['Preparation', 'Action', 'Maintenance'],
    explanation: 'The best answer is precontemplation because the patient does not recognize the behavior as a problem and has no intention to change.',
    pearl: 'In precontemplation, the best first step is to raise awareness and explore ambivalence.',
    trap: 'Preparation requires intention to change soon and often a specific plan.',
  }),
  q({
    id: 'qCOVBEH006',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Positive reinforcement increasing behavior',
    topic: 'Behavioral Conditioning',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'A child receives a sticker each time he completes his physical therapy exercises. Over the next month, he performs the exercises more consistently. Which behavioral principle is being used?',
    correct: 'Positive reinforcement',
    distractors: ['Negative reinforcement', 'Positive punishment', 'Response extinction'],
    explanation: 'The best answer is positive reinforcement because adding a rewarding stimulus after a behavior increases the likelihood of that behavior.',
    pearl: 'Positive means adding a stimulus; reinforcement means behavior increases.',
    trap: 'Negative reinforcement removes an aversive stimulus to increase behavior.',
  }),
  q({
    id: 'qCOVBEH007',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Illness anxiety disorder with minimal somatic symptoms',
    topic: 'Somatic Symptom Disorders',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'A 38-year-old man is preoccupied for 8 months with the fear that he has pancreatic cancer despite normal examination, laboratory testing, and imaging. He has minimal abdominal symptoms but repeatedly seeks reassurance. Which diagnosis is most likely?',
    correct: 'Illness anxiety disorder',
    distractors: ['Somatic symptom disorder', 'Delusional disorder', 'Factitious disorder'],
    explanation: 'The best answer is illness anxiety disorder because excessive health anxiety persists despite minimal somatic symptoms and reassuring evaluations.',
    pearl: 'Illness anxiety disorder centers on fear of disease; somatic symptom disorder centers on distressing physical symptoms.',
    trap: 'Factitious disorder involves intentional falsification without obvious external reward.',
  }),
  q({
    id: 'qCOVBEH008',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Motivational interviewing reflective listening',
    topic: 'Clinical Communication',
    contentArea: 'Social Sciences',
    angle: 'communication',
    stem: 'A patient with diabetes says, "I know my diet matters, but changing everything feels impossible." Which physician response best uses motivational interviewing?',
    correct: 'It sounds like you see the importance of change but feel overwhelmed by where to start.',
    distractors: ['You must follow the diet exactly or your diabetes will worsen.', 'Here is a strict meal plan; begin it tomorrow.', 'Your family should make sure you stop eating sweets.'],
    explanation: 'The best answer is It sounds like you see the importance of change but feel overwhelmed by where to start because reflective listening acknowledges ambivalence and supports autonomy.',
    pearl: 'Motivational interviewing uses open questions, affirmations, reflection, and summaries.',
    trap: 'Directive warnings can increase resistance when a patient is ambivalent.',
  }),
  q({
    id: 'qCOVBEH009',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Capacity requires understanding appreciation reasoning and choice',
    topic: 'Decision-Making Capacity',
    contentArea: 'Social Sciences',
    angle: 'ethics',
    stem: 'A hospitalized patient refuses a recommended procedure. He can describe his diagnosis, explain the risks and benefits, state how the decision applies to him, and communicate a stable choice. Which conclusion is most appropriate?',
    correct: 'He has decision-making capacity for this choice',
    distractors: ['He lacks capacity because he refuses recommended care', 'A family member must decide because he is hospitalized', 'Capacity can only be determined by a court'],
    explanation: 'The best answer is he has decision-making capacity for this choice because capacity requires understanding, appreciation, reasoning, and communication of a choice.',
    pearl: 'A patient can have capacity and still make a decision the physician disagrees with.',
    trap: 'Refusal of care alone does not prove incapacity.',
  }),
  q({
    id: 'qCOVBEH010',
    subject: 'Behavioral Science',
    system: 'Psychiatry',
    concept: 'Delirium with fluctuating attention and acute onset',
    topic: 'Neurocognitive Disorders',
    contentArea: 'Behavioral Health',
    angle: 'behavioral',
    stem: 'An 82-year-old woman becomes acutely confused after surgery. Her attention fluctuates during the day, and she is disoriented in the evening. Family reports she was independent and cognitively intact before admission. Which diagnosis best explains this presentation?',
    correct: 'Delirium',
    distractors: ['Alzheimer disease', 'Schizophrenia', 'Normal aging'],
    explanation: 'The best answer is delirium because acute onset, fluctuating course, and impaired attention distinguish it from chronic dementia.',
    pearl: 'Delirium is acute and fluctuating; dementia is chronic and progressive.',
    trap: 'Older age increases delirium risk, but acute inattention is not normal aging.',
  }),

  q({
    id: 'qCOVDERM001',
    subject: 'Pathology',
    system: 'Dermatology',
    concept: 'Psoriasis epidermal hyperproliferation',
    topic: 'Papulosquamous Skin Disease',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'pathology',
    stem: 'A 34-year-old man has well-demarcated erythematous plaques with silvery scale on the extensor elbows and knees. Nail pitting is present. Which pathologic process best explains these lesions?',
    correct: 'Keratinocyte hyperproliferation with abnormal epidermal differentiation',
    distractors: ['IgE-mediated mast cell degranulation', 'Loss of melanocytes in the basal layer', 'Deep dermal fungal invasion'],
    explanation: 'The best answer is keratinocyte hyperproliferation with abnormal epidermal differentiation because psoriasis produces thick scaly plaques from accelerated epidermal turnover.',
    pearl: 'Psoriasis classically affects extensor surfaces and may cause nail pitting.',
    trap: 'Atopic dermatitis is pruritic and flexural, not classic silvery extensor plaques.',
  }),
  q({
    id: 'qCOVDERM002',
    subject: 'Immunology',
    system: 'Dermatology',
    concept: 'Type IV hypersensitivity in allergic contact dermatitis',
    topic: 'Contact Dermatitis',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'immunology',
    stem: 'A woman develops a pruritic vesicular rash under a new nickel-containing bracelet 48 hours after first wearing it. Which immune mechanism best explains the delayed reaction?',
    correct: 'T cell mediated type IV hypersensitivity',
    distractors: ['IgE mediated type I hypersensitivity', 'Immune complex deposition', 'Complement C5-C9 deficiency'],
    explanation: 'The best answer is T cell mediated type IV hypersensitivity because allergic contact dermatitis is a delayed hypersensitivity reaction driven by sensitized T cells.',
    pearl: 'Contact dermatitis is delayed and localized to the exposure pattern.',
    trap: 'IgE-mediated reactions occur rapidly and often include urticaria or anaphylaxis.',
  }),
  q({
    id: 'qCOVDERM003',
    subject: 'Microbiology',
    system: 'Dermatology',
    concept: 'Impetigo from Staphylococcus aureus or Streptococcus pyogenes',
    topic: 'Bacterial Skin Infection',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'microbiology',
    stem: 'A 5-year-old child has honey-colored crusted erosions around the mouth after several days of scratching insect bites. Which organisms are the most common causes of this superficial infection?',
    correct: 'Staphylococcus aureus and Streptococcus pyogenes',
    distractors: ['Candida albicans and Malassezia furfur', 'Pseudomonas aeruginosa and Clostridium perfringens', 'Borrelia burgdorferi and Rickettsia rickettsii'],
    explanation: 'The best answer is Staphylococcus aureus and Streptococcus pyogenes because nonbullous impetigo commonly causes honey-colored crusts in children.',
    pearl: 'Impetigo is a superficial contagious bacterial infection with honey-colored crusting.',
    trap: 'Candida causes satellite lesions in moist areas, not classic honey-colored crusts.',
  }),
  q({
    id: 'qCOVDERM004',
    subject: 'Pharmacology',
    system: 'Dermatology',
    concept: 'Topical corticosteroid anti-inflammatory mechanism',
    topic: 'Dermatologic Pharmacology',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'pharmacology',
    stem: 'A patient with atopic dermatitis is treated with a topical corticosteroid. The pruritus and erythema improve. Which mechanism most directly accounts for the therapeutic effect?',
    correct: 'Reduced transcription of proinflammatory cytokines',
    distractors: ['Inhibition of fungal ergosterol synthesis', 'Blockade of bacterial cell wall cross-linking', 'Stimulation of histamine release'],
    explanation: 'The best answer is reduced transcription of proinflammatory cytokines because corticosteroids bind glucocorticoid receptors and suppress inflammatory gene expression.',
    pearl: 'Topical corticosteroids reduce local inflammation but can cause skin atrophy with prolonged use.',
    trap: 'Antifungals target ergosterol; they do not explain steroid response in dermatitis.',
  }),
  q({
    id: 'qCOVDERM005',
    subject: 'Pathology',
    system: 'Dermatology',
    concept: 'Basal cell carcinoma from UV-induced DNA damage',
    topic: 'Nonmelanoma Skin Cancer',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'pathology',
    stem: 'A 68-year-old man has a pearly papule with telangiectasias on the nose. Biopsy shows nests of basaloid cells with peripheral palisading. Which risk factor most strongly contributes to this lesion?',
    correct: 'Chronic ultraviolet radiation exposure',
    distractors: ['Epstein-Barr virus infection', 'High-risk human papillomavirus infection', 'Aflatoxin exposure'],
    explanation: 'The best answer is chronic ultraviolet radiation exposure because basal cell carcinoma commonly occurs on sun-exposed skin and shows basaloid nests with palisading.',
    pearl: 'Basal cell carcinoma is locally invasive and rarely metastasizes.',
    trap: 'High-risk HPV is linked to cervical and anogenital cancers, not classic pearly basal cell carcinoma.',
  }),
  q({
    id: 'qCOVDERM006',
    subject: 'Pathology',
    system: 'Dermatology',
    concept: 'Melanoma ABCDE warning signs',
    topic: 'Melanoma Recognition',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'pathology',
    stem: 'A 47-year-old woman has a pigmented lesion with asymmetry, irregular borders, color variation, diameter of 8 mm, and recent enlargement. Which diagnosis is most concerning?',
    correct: 'Melanoma',
    distractors: ['Seborrheic keratosis', 'Dermatofibroma', 'Cherry angioma'],
    explanation: 'The best answer is melanoma because ABCDE features--asymmetry, border irregularity, color variation, diameter greater than 6 mm, and evolution--suggest malignant melanoma.',
    pearl: 'Evolution is one of the most important warning signs for melanoma.',
    trap: 'Seborrheic keratosis is usually stuck-on and waxy rather than evolving with ABCDE features.',
  }),
  q({
    id: 'qCOVDERM007',
    subject: 'Immunology',
    system: 'Dermatology',
    concept: 'Pemphigus vulgaris desmoglein autoantibodies',
    topic: 'Autoimmune Blistering Disease',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'immunology',
    stem: 'A 55-year-old man has painful oral erosions and flaccid skin bullae that rupture easily. Gentle pressure causes epidermal sloughing. Autoantibodies against which structure best explain this disease?',
    correct: 'Desmoglein in desmosomes',
    distractors: ['Hemidesmosomal BP180 at the basement membrane', 'Type IV collagen in glomerular basement membrane', 'Keratin filaments in basal cells'],
    explanation: 'The best answer is desmoglein in desmosomes because pemphigus vulgaris causes intraepidermal acantholysis with flaccid bullae and mucosal erosions.',
    pearl: 'Pemphigus vulgaris has flaccid bullae and a positive Nikolsky sign.',
    trap: 'Bullous pemphigoid targets hemidesmosomes and causes tense bullae with less mucosal involvement.',
  }),
  q({
    id: 'qCOVDERM008',
    subject: 'Microbiology',
    system: 'Dermatology',
    concept: 'Dermatophyte infection diagnosed by KOH hyphae',
    topic: 'Superficial Fungal Infection',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'microbiology',
    stem: 'A wrestler has an annular pruritic plaque with central clearing on the trunk. Potassium hydroxide preparation of skin scrapings shows branching septate hyphae. Which diagnosis is most likely?',
    correct: 'Tinea corporis',
    distractors: ['Herpes zoster', 'Erythema migrans', 'Scabies'],
    explanation: 'The best answer is tinea corporis because dermatophyte infection causes annular scaly plaques with central clearing and KOH branching septate hyphae.',
    pearl: 'Dermatophytes infect keratinized tissue: skin, hair, and nails.',
    trap: 'Erythema migrans expands after tick exposure and does not show KOH hyphae.',
  }),
  q({
    id: 'qCOVDERM009',
    subject: 'Physiology',
    system: 'Dermatology',
    concept: 'Eccrine sweat gland sympathetic cholinergic innervation',
    topic: 'Sweat Gland Physiology',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'physiology',
    stem: 'During exercise in a hot environment, a healthy person increases sweating from eccrine glands. Which autonomic neurotransmitter is primarily responsible for stimulating these glands?',
    correct: 'Acetylcholine from sympathetic postganglionic fibers',
    distractors: ['Norepinephrine from parasympathetic postganglionic fibers', 'Dopamine from adrenal medulla', 'Serotonin from sensory neurons'],
    explanation: 'The best answer is acetylcholine from sympathetic postganglionic fibers because eccrine sweat glands are an exception: sympathetic fibers release acetylcholine.',
    pearl: 'Most sympathetic postganglionic fibers release norepinephrine; eccrine sweat glands use acetylcholine.',
    trap: 'Parasympathetic fibers are not the primary innervation of eccrine sweating.',
  }),
  q({
    id: 'qCOVDERM010',
    subject: 'Pharmacology',
    system: 'Dermatology',
    concept: 'Isotretinoin teratogenicity and iPLEDGE',
    topic: 'Acne Pharmacology',
    contentArea: 'Skin & Subcutaneous Tissue',
    angle: 'pharmacology',
    stem: 'A 19-year-old woman with severe nodulocystic acne is prescribed isotretinoin. Which counseling point is most important before starting therapy?',
    correct: 'Strict pregnancy prevention because isotretinoin is highly teratogenic',
    distractors: ['Avoid tyramine-containing foods to prevent hypertensive crisis', 'Take folinic acid rescue after each dose', 'Expect permanent infertility after completion'],
    explanation: 'The best answer is strict pregnancy prevention because isotretinoin is highly teratogenic and requires pregnancy testing and contraception precautions.',
    pearl: 'Isotretinoin treats severe acne but is teratogenic and can cause mucocutaneous dryness and hypertriglyceridemia.',
    trap: 'Tyramine restriction applies to monoamine oxidase inhibitors, not isotretinoin.',
  }),

  q({
    id: 'qCOVONC001',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Adenoma-carcinoma sequence from APC to KRAS to TP53',
    topic: 'Colorectal Carcinogenesis',
    contentArea: 'Gastrointestinal System',
    angle: 'pathology',
    stem: 'A colon polyp progresses over years to invasive adenocarcinoma. Molecular testing shows early APC loss followed by KRAS activation and later TP53 loss. Which model of carcinogenesis is illustrated?',
    correct: 'Stepwise accumulation of driver mutations',
    distractors: ['Immediate malignant transformation after one mutation', 'Purely infectious transformation by a DNA virus', 'Mitochondrial inheritance of malignant cells'],
    explanation: 'The best answer is stepwise accumulation of driver mutations because colorectal cancer often develops through sequential APC, KRAS, and TP53 alterations.',
    pearl: 'The adenoma-carcinoma sequence is a classic multistep cancer progression model.',
    trap: 'One mutation is usually insufficient for common epithelial malignancies.',
  }),
  q({
    id: 'qCOVONC002',
    subject: 'Genetics',
    system: 'Oncology',
    concept: 'BRCA1 homologous recombination repair defect',
    topic: 'DNA Repair Cancer Syndromes',
    contentArea: 'Female and Transgender Reproductive System & Breast',
    angle: 'genetics',
    stem: 'A 39-year-old woman with triple-negative breast cancer has a strong family history of breast and ovarian cancer. Germline testing shows a BRCA1 pathogenic variant. Which DNA repair process is impaired?',
    correct: 'Homologous recombination repair of double-strand breaks',
    distractors: ['Nucleotide excision repair of pyrimidine dimers', 'Mismatch repair of replication errors', 'Base excision repair of uracil residues'],
    explanation: 'The best answer is homologous recombination repair of double-strand breaks because BRCA1 and BRCA2 participate in high-fidelity double-strand break repair.',
    pearl: 'BRCA mutations increase breast, ovarian, pancreatic, and prostate cancer risk.',
    trap: 'Mismatch repair defects cause Lynch syndrome with microsatellite instability.',
  }),
  q({
    id: 'qCOVONC003',
    subject: 'Pharmacology',
    system: 'Oncology',
    concept: 'Imatinib inhibition of BCR-ABL tyrosine kinase',
    topic: 'Targeted Cancer Therapy',
    contentArea: 'Blood & Lymphoreticular System',
    angle: 'pharmacology',
    stem: 'A patient with chronic myeloid leukemia has a t(9;22) translocation and is treated with imatinib. Which molecular target is directly inhibited by this drug?',
    correct: 'BCR-ABL tyrosine kinase',
    distractors: ['HER2 receptor extracellular domain', 'PD-1 immune checkpoint receptor', 'Estrogen receptor in breast tissue'],
    explanation: 'The best answer is BCR-ABL tyrosine kinase because imatinib blocks the constitutively active kinase produced by the Philadelphia chromosome.',
    pearl: 'CML is associated with t(9;22), forming the BCR-ABL fusion protein.',
    trap: 'Trastuzumab targets HER2, not BCR-ABL.',
  }),
  q({
    id: 'qCOVONC004',
    subject: 'Immunology',
    system: 'Oncology',
    concept: 'PD-1 checkpoint blockade restoring T cell activity',
    topic: 'Cancer Immunotherapy',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'immunology',
    stem: 'A patient with metastatic melanoma improves after receiving an antibody that blocks PD-1. Which mechanism best explains the antitumor effect?',
    correct: 'Restoration of exhausted T cell activity against tumor cells',
    distractors: ['Direct alkylation of tumor DNA', 'Inhibition of fungal ergosterol synthesis', 'Chelation of circulating calcium'],
    explanation: 'The best answer is restoration of exhausted T cell activity against tumor cells because PD-1 blockade releases inhibitory checkpoint signaling.',
    pearl: 'Checkpoint inhibitors can cause immune-related adverse events due to increased T cell activity.',
    trap: 'Checkpoint inhibitors do not directly alkylate DNA like cyclophosphamide.',
  }),
  q({
    id: 'qCOVONC005',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Warburg effect increased aerobic glycolysis',
    topic: 'Cancer Metabolism',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'pathology',
    stem: 'A rapidly growing tumor shows high glucose uptake on PET imaging even in the presence of adequate oxygen. Which metabolic adaptation best explains this finding?',
    correct: 'Increased aerobic glycolysis',
    distractors: ['Complete shutdown of glucose transporters', 'Exclusive fatty acid oxidation', 'Failure of lactate production'],
    explanation: 'The best answer is increased aerobic glycolysis because many cancers preferentially convert glucose to lactate despite oxygen availability, known as the Warburg effect.',
    pearl: 'FDG-PET exploits increased tumor glucose uptake.',
    trap: 'Tumors often increase, not decrease, glucose transporter activity.',
  }),
  q({
    id: 'qCOVONC006',
    subject: 'Biochemistry',
    system: 'Oncology',
    concept: 'Methotrexate inhibition of dihydrofolate reductase',
    topic: 'Antimetabolite Chemotherapy',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'biochemistry',
    stem: 'A chemotherapy drug decreases thymidylate synthesis by preventing regeneration of tetrahydrofolate. Which enzyme is directly inhibited?',
    correct: 'Dihydrofolate reductase',
    distractors: ['Thymidine kinase', 'Ribonucleotide reductase', 'Adenylate cyclase'],
    explanation: 'The best answer is dihydrofolate reductase because methotrexate blocks DHFR, decreasing tetrahydrofolate and impairing DNA synthesis.',
    pearl: 'Methotrexate toxicity can be rescued with leucovorin, a reduced folate.',
    trap: 'Hydroxyurea inhibits ribonucleotide reductase, not DHFR.',
  }),
  q({
    id: 'qCOVONC007',
    subject: 'Microbiology',
    system: 'Oncology',
    concept: 'HPV E6 and E7 in cervical carcinogenesis',
    topic: 'Oncogenic Viruses',
    contentArea: 'Female and Transgender Reproductive System & Breast',
    angle: 'microbiology',
    stem: 'A cervical biopsy shows high-grade squamous intraepithelial lesion associated with high-risk HPV infection. Which viral proteins promote malignant transformation?',
    correct: 'E6 degradation of p53 and E7 inhibition of Rb',
    distractors: ['gp120 binding to CD4 and CCR5', 'M protein inhibition of phagocytosis', 'Shiga toxin inactivation of 60S ribosome'],
    explanation: 'The best answer is E6 degradation of p53 and E7 inhibition of Rb because high-risk HPV disables key tumor suppressor pathways.',
    pearl: 'High-risk HPV types 16 and 18 are strongly linked to cervical and anogenital cancers.',
    trap: 'HIV gp120 mediates viral entry and is not the direct HPV oncogenic mechanism.',
  }),
  q({
    id: 'qCOVONC008',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Grading versus staging in cancer prognosis',
    topic: 'Cancer Prognosis',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'pathology',
    stem: 'A pathology report describes a colon adenocarcinoma as poorly differentiated, and imaging shows liver metastases. Which statement best distinguishes grading from staging?',
    correct: 'Grade describes differentiation; stage describes extent of spread',
    distractors: ['Grade describes tumor size only; stage describes mitotic rate only', 'Grade and stage both describe only histologic atypia', 'Stage describes differentiation; grade describes nodal spread'],
    explanation: 'The best answer is grade describes differentiation; stage describes extent of spread because histologic grade and anatomic stage provide different prognostic information.',
    pearl: 'Stage is usually the strongest predictor of prognosis for solid tumors.',
    trap: 'Poor differentiation is grade, not stage.',
  }),
  q({
    id: 'qCOVONC009',
    subject: 'Pharmacology',
    system: 'Oncology',
    concept: 'Cyclophosphamide hemorrhagic cystitis from acrolein',
    topic: 'Chemotherapy Toxicity',
    contentArea: 'Renal & Urinary System',
    angle: 'pharmacology',
    stem: 'A patient receiving chemotherapy develops hematuria and bladder irritation. The oncologist adds mesna to future cycles. Which toxic metabolite is being neutralized?',
    correct: 'Acrolein',
    distractors: ['Doxorubicinol', 'Bleomycin hydrolase', 'All-trans retinoic acid'],
    explanation: 'The best answer is acrolein because cyclophosphamide can cause hemorrhagic cystitis through acrolein, and mesna binds this toxic metabolite.',
    pearl: 'Mesna prevents cyclophosphamide-associated hemorrhagic cystitis.',
    trap: 'Doxorubicin toxicity is classically cardiomyopathy, not acrolein bladder injury.',
  }),
  q({
    id: 'qCOVONC010',
    subject: 'Genetics',
    system: 'Oncology',
    concept: 'Lynch syndrome mismatch repair deficiency',
    topic: 'Mismatch Repair Cancer Syndrome',
    contentArea: 'Gastrointestinal System',
    angle: 'genetics',
    stem: 'A 42-year-old man develops right-sided colon cancer. His mother had endometrial cancer at age 45. Tumor testing shows microsatellite instability. Which inherited defect best explains this syndrome?',
    correct: 'Mismatch repair gene loss',
    distractors: ['APC tumor suppressor loss with hundreds of polyps', 'RET proto-oncogene activation', 'FBN1 microfibril defect'],
    explanation: 'The best answer is mismatch repair gene loss because Lynch syndrome causes microsatellite instability and increases colon and endometrial cancer risk.',
    pearl: 'Lynch syndrome often causes right-sided colon cancer with few polyps.',
    trap: 'Familial adenomatous polyposis causes hundreds to thousands of adenomatous polyps from APC loss.',
  }),

  q({
    id: 'qCOVPCV001',
    subject: 'Pharmacology',
    system: 'Cardiovascular',
    concept: 'Beta blocker mortality benefit after myocardial infarction',
    topic: 'Post-MI Pharmacotherapy',
    contentArea: 'Cardiovascular System',
    angle: 'pharmacology',
    stem: 'A 58-year-old man is discharged after an uncomplicated myocardial infarction. He is started on aspirin, a statin, an ACE inhibitor, and metoprolol. Which effect of metoprolol most directly improves survival after myocardial infarction?',
    correct: 'Reduced sympathetic stimulation and myocardial oxygen demand',
    distractors: ['Direct dissolution of coronary thrombus', 'Increased renal potassium excretion', 'Blockade of platelet cyclooxygenase'],
    explanation: 'The best answer is reduced sympathetic stimulation and myocardial oxygen demand because beta blockers decrease heart rate, contractility, and arrhythmia risk after myocardial infarction.',
    pearl: 'Beta blockers after MI reduce mortality by lowering sympathetic stress and arrhythmic death.',
    trap: 'Aspirin blocks platelet cyclooxygenase; beta blockers do not directly inhibit platelets.',
  }),
  q({
    id: 'qCOVPCV002',
    subject: 'Pharmacology',
    system: 'Cardiovascular',
    concept: 'ACE inhibitor reduction of angiotensin II and aldosterone',
    topic: 'Heart Failure Pharmacotherapy',
    contentArea: 'Cardiovascular System',
    angle: 'pharmacology',
    stem: 'A patient with systolic heart failure is started on lisinopril. Over time, afterload decreases and maladaptive ventricular remodeling slows. Which biochemical change best explains this benefit?',
    correct: 'Decreased angiotensin II formation',
    distractors: ['Increased calcium influx through L-type channels', 'Direct activation of beta-1 receptors', 'Inhibition of sodium-glucose cotransporter 2 in myocardium'],
    explanation: 'The best answer is decreased angiotensin II formation because ACE inhibitors reduce angiotensin II and aldosterone, lowering afterload and limiting remodeling in heart failure.',
    pearl: 'ACE inhibitors can cause cough and angioedema from increased bradykinin.',
    trap: 'Calcium channel activation would increase contractility and is not the ACE inhibitor mechanism.',
  }),
  q({
    id: 'qCOVPCV003',
    subject: 'Pharmacology',
    system: 'Cardiovascular',
    concept: 'Nitroglycerin venodilation decreasing preload',
    topic: 'Antianginal Pharmacology',
    contentArea: 'Cardiovascular System',
    angle: 'pharmacology',
    stem: 'A 63-year-old man with exertional chest pain takes sublingual nitroglycerin and rapidly improves. Which hemodynamic effect most directly reduces his myocardial oxygen demand?',
    correct: 'Venodilation with decreased preload',
    distractors: ['Increased systemic vascular resistance', 'Irreversible platelet ADP receptor blockade', 'Increased sinoatrial node automaticity'],
    explanation: 'The best answer is venodilation with decreased preload because nitrates release nitric oxide, increase cGMP, and reduce ventricular wall stress.',
    pearl: 'Nitrates mainly reduce preload; reflex tachycardia and headache can occur.',
    trap: 'Clopidogrel blocks platelet ADP receptors, not nitroglycerin.',
  }),
  q({
    id: 'qCOVPCV004',
    subject: 'Pharmacology',
    system: 'Cardiovascular',
    concept: 'Dihydropyridine calcium channel blockers causing arteriolar dilation',
    topic: 'Antihypertensive Pharmacology',
    contentArea: 'Cardiovascular System',
    angle: 'pharmacology',
    stem: 'A patient with hypertension starts amlodipine and develops ankle edema and flushing. Which vascular effect best explains both the therapeutic and adverse effects?',
    correct: 'Arteriolar smooth muscle relaxation from L-type calcium channel blockade',
    distractors: ['Venous nitric oxide release with selective preload reduction', 'Mineralocorticoid receptor antagonism in collecting ducts', 'Beta-1 receptor blockade in the sinoatrial node'],
    explanation: 'The best answer is arteriolar smooth muscle relaxation from L-type calcium channel blockade because dihydropyridines lower blood pressure by vasodilation and can cause edema and flushing.',
    pearl: 'Dihydropyridines act mainly on vascular smooth muscle; non-dihydropyridines act more on the heart.',
    trap: 'Ankle edema from amlodipine is not primarily due to renal sodium retention.',
  }),
  q({
    id: 'qCOVPCV005',
    subject: 'Pharmacology',
    system: 'Cardiovascular',
    concept: 'Amiodarone class III antiarrhythmic potassium channel blockade',
    topic: 'Antiarrhythmic Pharmacology',
    contentArea: 'Cardiovascular System',
    angle: 'pharmacology',
    stem: 'A patient with recurrent ventricular tachycardia is treated with amiodarone. Follow-up shows QT prolongation, elevated thyroid-stimulating hormone, and new pulmonary symptoms. Which primary electrophysiologic action treats the arrhythmia?',
    correct: 'Potassium channel blockade prolonging phase 3 repolarization',
    distractors: ['Opening ATP-sensitive potassium channels', 'Selective alpha-1 receptor stimulation', 'Irreversible inhibition of vitamin K epoxide reductase'],
    explanation: 'The best answer is potassium channel blockade prolonging phase 3 repolarization because amiodarone is a class III antiarrhythmic with thyroid and pulmonary toxicities.',
    pearl: 'Amiodarone can cause pulmonary fibrosis, thyroid dysfunction, liver toxicity, and corneal deposits.',
    trap: 'Warfarin inhibits vitamin K epoxide reductase; it is not an antiarrhythmic.',
  }),

  q({
    id: 'qCOVPATCV001',
    subject: 'Pathology',
    system: 'Cardiovascular',
    concept: 'Coagulative necrosis after myocardial infarction',
    topic: 'Myocardial Infarction Pathology',
    contentArea: 'Cardiovascular System',
    angle: 'pathology',
    stem: 'A man dies 24 hours after severe chest pain from an occluded coronary artery. Microscopy of the affected myocardium shows hypereosinophilic myocytes with loss of nuclei and preserved tissue architecture. Which type of necrosis is present?',
    correct: 'Coagulative necrosis',
    distractors: ['Liquefactive necrosis', 'Caseous necrosis', 'Fat necrosis'],
    explanation: 'The best answer is coagulative necrosis because ischemic infarction in solid organs such as myocardium preserves tissue architecture early after cell death.',
    pearl: 'Brain infarcts cause liquefactive necrosis; myocardial infarcts cause coagulative necrosis.',
    trap: 'Liquefactive necrosis is typical of abscesses and CNS infarcts, not myocardial infarction.',
  }),
  q({
    id: 'qCOVPATCV002',
    subject: 'Pathology',
    system: 'Cardiovascular',
    concept: 'Atherosclerotic plaque rupture causing acute coronary thrombosis',
    topic: 'Atherosclerosis Complications',
    contentArea: 'Cardiovascular System',
    angle: 'pathology',
    stem: 'A 61-year-old man suddenly develops crushing chest pain. Coronary angiography shows an occlusive thrombus overlying a disrupted lipid-rich plaque. Which event most directly triggered the acute occlusion?',
    correct: 'Fibrous cap rupture exposing thrombogenic plaque contents',
    distractors: ['Stable plaque calcification without surface disruption', 'Diffuse arteriolar hyaline deposition', 'Primary venous valve incompetence'],
    explanation: 'The best answer is fibrous cap rupture exposing thrombogenic plaque contents because acute coronary syndromes often result from thrombosis after plaque disruption.',
    pearl: 'Plaques with thin fibrous caps and large lipid cores are prone to rupture.',
    trap: 'Stable calcified plaques can cause chronic angina but are less likely to cause acute thrombosis.',
  }),
  q({
    id: 'qCOVPATCV003',
    subject: 'Pathology',
    system: 'Cardiovascular',
    concept: 'Rheumatic heart disease from molecular mimicry',
    topic: 'Valvular Heart Disease',
    contentArea: 'Cardiovascular System',
    angle: 'pathology',
    stem: 'A teenager develops migratory polyarthritis and a new murmur several weeks after untreated streptococcal pharyngitis. Years later, echocardiography shows mitral stenosis. Which mechanism caused the valve injury?',
    correct: 'Cross-reactive antibodies against streptococcal and cardiac antigens',
    distractors: ['Direct bacterial invasion of valve leaflets', 'Deposition of monosodium urate crystals', 'IgE-mediated mast cell degranulation'],
    explanation: 'The best answer is cross-reactive antibodies against streptococcal and cardiac antigens because rheumatic fever results from molecular mimicry after group A streptococcal infection.',
    pearl: 'Rheumatic heart disease most commonly affects the mitral valve.',
    trap: 'Acute rheumatic fever is immune mediated, not direct bacterial infection of the valve.',
  }),
  q({
    id: 'qCOVPATCV004',
    subject: 'Pathology',
    system: 'Cardiovascular',
    concept: 'Cardiac tamponade causing equalization of diastolic pressures',
    topic: 'Pericardial Disease',
    contentArea: 'Cardiovascular System',
    angle: 'pathology',
    stem: 'A trauma patient becomes hypotensive with jugular venous distention and muffled heart sounds. Echocardiography shows blood in the pericardial sac compressing the heart. Which hemodynamic change is expected?',
    correct: 'Impaired ventricular filling with equalized diastolic pressures',
    distractors: ['Increased left ventricular compliance', 'Isolated systolic hypertension from increased stroke volume', 'Reduced pulmonary vascular resistance from nitric oxide excess'],
    explanation: 'The best answer is impaired ventricular filling with equalized diastolic pressures because tamponade restricts diastolic filling of all chambers.',
    pearl: 'Beck triad: hypotension, jugular venous distention, and muffled heart sounds.',
    trap: 'Tamponade decreases stroke volume; it does not cause isolated systolic hypertension.',
  }),
  q({
    id: 'qCOVPATCV005',
    subject: 'Pathology',
    system: 'Cardiovascular',
    concept: 'Hypertrophic cardiomyopathy from sarcomere mutation',
    topic: 'Cardiomyopathy Pathology',
    contentArea: 'Cardiovascular System',
    angle: 'pathology',
    stem: 'A young athlete collapses during exercise. Autopsy shows asymmetric septal hypertrophy, myofiber disarray, and a small left ventricular outflow tract. Which underlying abnormality most commonly causes this condition?',
    correct: 'Autosomal dominant mutation in a sarcomere protein',
    distractors: ['Amyloid deposition in the atria only', 'Chronic viral destruction of the mitral valve', 'Congenital absence of the pericardium'],
    explanation: 'The best answer is autosomal dominant mutation in a sarcomere protein because hypertrophic cardiomyopathy is commonly due to mutations in beta-myosin heavy chain or myosin-binding protein C.',
    pearl: 'Hypertrophic cardiomyopathy can cause sudden death in young athletes.',
    trap: 'Athletic heart is physiologic and lacks myofiber disarray.',
  }),

  q({
    id: 'qCOVPHYREN001',
    subject: 'Physiology',
    system: 'Renal / Urinary',
    concept: 'Afferent arteriole dilation increases GFR',
    topic: 'Glomerular Filtration Physiology',
    contentArea: 'Renal & Urinary System',
    angle: 'physiology',
    stem: 'An experimental drug selectively dilates the afferent arteriole of the kidney without changing the efferent arteriole. Which change is expected in glomerular filtration rate?',
    correct: 'Increased GFR from increased glomerular capillary hydrostatic pressure',
    distractors: ['Decreased GFR from decreased renal plasma flow', 'No change because afferent tone does not affect filtration', 'Decreased GFR from increased Bowman space pressure'],
    explanation: 'The best answer is increased GFR from increased glomerular capillary hydrostatic pressure because afferent arteriole dilation raises pressure entering the glomerulus.',
    pearl: 'Afferent dilation increases renal plasma flow and usually increases GFR.',
    trap: 'Bowman space pressure rises in obstruction, not isolated afferent dilation.',
  }),
  q({
    id: 'qCOVPHYREN002',
    subject: 'Physiology',
    system: 'Renal / Urinary',
    concept: 'Countercurrent multiplication depends on thick ascending limb salt transport',
    topic: 'Urine Concentration',
    contentArea: 'Renal & Urinary System',
    angle: 'physiology',
    stem: 'A research subject receives a drug that inhibits sodium-potassium-chloride transport in the thick ascending limb. Which renal concentrating mechanism is directly impaired?',
    correct: 'Medullary hypertonicity generated by countercurrent multiplication',
    distractors: ['Water reabsorption in the proximal tubule by aquaporin-1 only', 'Bicarbonate reclamation by carbonic anhydrase in red blood cells', 'Glucose filtration at the glomerular basement membrane'],
    explanation: 'The best answer is medullary hypertonicity generated by countercurrent multiplication because NKCC transport in the thick ascending limb creates the corticomedullary gradient.',
    pearl: 'The thick ascending limb is diluting and water impermeable.',
    trap: 'ADH uses the medullary gradient but does not create it alone.',
  }),
  q({
    id: 'qCOVPHYREN003',
    subject: 'Physiology',
    system: 'Renal / Urinary',
    concept: 'Type A intercalated cells secrete hydrogen ions',
    topic: 'Acid-Base Renal Physiology',
    contentArea: 'Renal & Urinary System',
    angle: 'physiology',
    stem: 'During metabolic acidosis, cells in the collecting duct increase hydrogen ion secretion and regenerate bicarbonate. Which cell type is primarily responsible for this response?',
    correct: 'Type A intercalated cells',
    distractors: ['Principal cells', 'Macula densa cells', 'Podocytes'],
    explanation: 'The best answer is Type A intercalated cells because they secrete hydrogen ions and reabsorb bicarbonate during acidemia.',
    pearl: 'Type A intercalated cells handle acidosis; Type B intercalated cells secrete bicarbonate in alkalosis.',
    trap: 'Principal cells regulate sodium reabsorption and potassium secretion under aldosterone.',
  }),
  q({
    id: 'qCOVPHYREN004',
    subject: 'Physiology',
    system: 'Renal / Urinary',
    concept: 'Macula densa tubuloglomerular feedback',
    topic: 'Tubuloglomerular Feedback',
    contentArea: 'Renal & Urinary System',
    angle: 'physiology',
    stem: 'Increased sodium chloride delivery to the macula densa triggers adenosine release and constriction of the afferent arteriole. What is the purpose of this feedback response?',
    correct: 'Reduce GFR toward normal',
    distractors: ['Increase renin release by granular cells', 'Increase proximal glucose reabsorption above transport maximum', 'Increase Bowman space pressure'],
    explanation: 'The best answer is reduce GFR toward normal because tubuloglomerular feedback uses macula densa sensing of sodium chloride delivery to adjust afferent tone.',
    pearl: 'High macula densa NaCl suppresses renin and constricts the afferent arteriole.',
    trap: 'Low macula densa NaCl stimulates renin release, not high NaCl.',
  }),
  q({
    id: 'qCOVPHYREN005',
    subject: 'Physiology',
    system: 'Renal / Urinary',
    concept: 'Aldosterone increases ENaC-mediated sodium reabsorption',
    topic: 'Distal Nephron Physiology',
    contentArea: 'Renal & Urinary System',
    angle: 'physiology',
    stem: 'A patient with volume depletion has increased aldosterone secretion. In principal cells of the collecting duct, which transporter effect is expected?',
    correct: 'Increased epithelial sodium channel expression',
    distractors: ['Decreased Na-K ATPase activity', 'Inhibition of NKCC in the thick ascending limb', 'Closure of aquaporin-2 channels despite ADH'],
    explanation: 'The best answer is increased epithelial sodium channel expression because aldosterone increases ENaC and Na-K ATPase activity, promoting sodium reabsorption and potassium secretion.',
    pearl: 'Aldosterone acts on principal cells to retain sodium and excrete potassium.',
    trap: 'Loop diuretics inhibit NKCC, not aldosterone.',
  }),

  q({
    id: 'qCOVPREN001',
    subject: 'Pharmacology',
    system: 'Renal / Urinary',
    concept: 'Loop diuretics inhibit NKCC in the thick ascending limb',
    topic: 'Diuretic Pharmacology',
    contentArea: 'Renal & Urinary System',
    angle: 'pharmacology',
    stem: 'A patient with pulmonary edema receives furosemide and develops hypokalemia. Which transporter is directly inhibited by this medication?',
    correct: 'Na-K-2Cl cotransporter in the thick ascending limb',
    distractors: ['Na-Cl cotransporter in the distal convoluted tubule', 'Epithelial sodium channel in the collecting duct', 'SGLT2 in the proximal tubule'],
    explanation: 'The best answer is Na-K-2Cl cotransporter in the thick ascending limb because loop diuretics inhibit NKCC, increasing sodium delivery distally and promoting potassium loss.',
    pearl: 'Loop diuretics can cause hypokalemia, ototoxicity, and metabolic alkalosis.',
    trap: 'Thiazides inhibit the Na-Cl cotransporter in the distal convoluted tubule.',
  }),
  q({
    id: 'qCOVPREN002',
    subject: 'Pharmacology',
    system: 'Renal / Urinary',
    concept: 'Thiazide diuretics increase calcium reabsorption',
    topic: 'Thiazide Pharmacology',
    contentArea: 'Renal & Urinary System',
    angle: 'pharmacology',
    stem: 'A patient with recurrent calcium kidney stones is treated with hydrochlorothiazide. Which renal effect helps reduce urinary calcium excretion?',
    correct: 'Increased calcium reabsorption in the distal convoluted tubule',
    distractors: ['Decreased calcium reabsorption in the thick ascending limb', 'Direct dissolution of calcium oxalate crystals', 'Blockade of aldosterone receptors in collecting ducts'],
    explanation: 'The best answer is increased calcium reabsorption in the distal convoluted tubule because thiazides lower urinary calcium and can reduce calcium stone recurrence.',
    pearl: 'Thiazides waste potassium but retain calcium.',
    trap: 'Loop diuretics increase urinary calcium excretion.',
  }),
  q({
    id: 'qCOVPREN003',
    subject: 'Pharmacology',
    system: 'Renal / Urinary',
    concept: 'Acetazolamide carbonic anhydrase inhibition causing bicarbonaturia',
    topic: 'Carbonic Anhydrase Inhibitors',
    contentArea: 'Renal & Urinary System',
    angle: 'pharmacology',
    stem: 'A climber takes acetazolamide to prevent acute mountain sickness and develops alkaline urine with mild metabolic acidosis. Which proximal tubule process is inhibited?',
    correct: 'Carbonic anhydrase mediated bicarbonate reclamation',
    distractors: ['Aldosterone receptor activation', 'Na-K-2Cl cotransport in the thick ascending limb', 'ADH-mediated aquaporin insertion'],
    explanation: 'The best answer is carbonic anhydrase mediated bicarbonate reclamation because acetazolamide causes bicarbonaturia and a non-anion gap metabolic acidosis.',
    pearl: 'Acetazolamide alkalinizes urine and acidifies blood.',
    trap: 'ADH regulates water reabsorption in collecting ducts, not bicarbonate reclamation.',
  }),
  q({
    id: 'qCOVPREN004',
    subject: 'Pharmacology',
    system: 'Renal / Urinary',
    concept: 'Spironolactone mineralocorticoid receptor antagonism',
    topic: 'Potassium-Sparing Diuretics',
    contentArea: 'Renal & Urinary System',
    angle: 'pharmacology',
    stem: 'A patient with heart failure starts spironolactone and later develops hyperkalemia and breast tenderness. Which receptor is directly antagonized by this drug?',
    correct: 'Mineralocorticoid receptor',
    distractors: ['Beta-1 adrenergic receptor', 'Vasopressin V2 receptor', 'Angiotensin-converting enzyme'],
    explanation: 'The best answer is mineralocorticoid receptor because spironolactone blocks aldosterone action in collecting duct principal cells and can cause hyperkalemia and gynecomastia.',
    pearl: 'Spironolactone is potassium-sparing and antiandrogenic.',
    trap: 'ACE inhibitors reduce angiotensin II formation but do not directly block aldosterone receptors.',
  }),
  q({
    id: 'qCOVPREN005',
    subject: 'Pharmacology',
    system: 'Renal / Urinary',
    concept: 'SGLT2 inhibitors increase urinary glucose excretion',
    topic: 'Diabetes Renal Pharmacology',
    contentArea: 'Renal & Urinary System',
    angle: 'pharmacology',
    stem: 'A patient with type 2 diabetes starts empagliflozin. Urinalysis shows increased glucose excretion despite improved blood glucose control. Which transporter is inhibited?',
    correct: 'Sodium-glucose cotransporter 2 in the proximal tubule',
    distractors: ['Na-Cl cotransporter in the distal convoluted tubule', 'Aquaporin-2 in the collecting duct', 'Organic anion transporter in the loop of Henle'],
    explanation: 'The best answer is sodium-glucose cotransporter 2 in the proximal tubule because SGLT2 inhibitors reduce glucose reabsorption and increase glucosuria.',
    pearl: 'SGLT2 inhibitors can reduce heart failure hospitalization but increase genital mycotic infection risk.',
    trap: 'Aquaporin-2 controls water reabsorption in response to ADH, not glucose transport.',
  }),

  q({
    id: 'qCOVPATONC001',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Invasion through basement membrane defines carcinoma malignancy',
    topic: 'Cancer Invasion',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'pathology',
    stem: 'A breast biopsy shows atypical epithelial cells filling ducts. A later specimen shows the same cells extending through the basement membrane into surrounding stroma. Which change establishes invasive carcinoma?',
    correct: 'Penetration of the basement membrane',
    distractors: ['Increased nuclear size within an intact duct', 'Presence of mitotic figures only', 'Keratin production by epithelial cells'],
    explanation: 'The best answer is penetration of the basement membrane because invasion through the basement membrane distinguishes carcinoma in situ from invasive carcinoma.',
    pearl: 'Carcinoma in situ respects the basement membrane; invasive carcinoma breaches it.',
    trap: 'Cytologic atypia alone does not prove invasion.',
  }),
  q({
    id: 'qCOVPATONC002',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Tumor angiogenesis driven by VEGF',
    topic: 'Tumor Angiogenesis',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'pathology',
    stem: 'A growing solid tumor develops hypoxic regions and begins secreting factors that stimulate new blood vessel formation. Which mediator most directly drives this angiogenic response?',
    correct: 'Vascular endothelial growth factor',
    distractors: ['Erythropoietin from peritubular fibroblasts', 'Surfactant protein A from pneumocytes', 'Intrinsic factor from parietal cells'],
    explanation: 'The best answer is vascular endothelial growth factor because hypoxic tumors upregulate VEGF to promote angiogenesis and support growth.',
    pearl: 'VEGF promotes endothelial proliferation and vascular permeability.',
    trap: 'Erythropoietin increases red blood cell production, not local tumor angiogenesis.',
  }),
  q({
    id: 'qCOVPATONC003',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Cachexia from inflammatory cytokines in malignancy',
    topic: 'Cancer Cachexia',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'pathology',
    stem: 'A patient with advanced pancreatic cancer has profound weight loss, muscle wasting, anorexia, and fatigue despite adequate nutritional supplementation. Which mechanism best explains this syndrome?',
    correct: 'Cytokine-mediated hypermetabolism and proteolysis',
    distractors: ['Pure starvation with normal inflammatory signaling', 'Excess insulin secretion causing fat storage', 'Increased skeletal muscle hypertrophy'],
    explanation: 'The best answer is cytokine-mediated hypermetabolism and proteolysis because cancer cachexia reflects inflammatory mediators such as TNF and IL-1 driving wasting.',
    pearl: 'Cancer cachexia is not fully reversed by calories alone.',
    trap: 'Simple starvation preserves lean body mass better than inflammatory cachexia.',
  }),
  q({
    id: 'qCOVPATONC004',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Paraneoplastic Cushing syndrome from ectopic ACTH',
    topic: 'Paraneoplastic Syndromes',
    contentArea: 'Endocrine System',
    angle: 'pathology',
    stem: 'A heavy smoker has weight gain, proximal muscle weakness, hyperglycemia, hypokalemia, and a lung mass. Laboratory testing shows markedly elevated ACTH. Which tumor type is classically associated with this paraneoplastic syndrome?',
    correct: 'Small cell lung carcinoma',
    distractors: ['Squamous cell carcinoma producing parathyroid hormone-related peptide only', 'Basal cell carcinoma of the skin', 'Papillary thyroid carcinoma'],
    explanation: 'The best answer is small cell lung carcinoma because it can produce ectopic ACTH, causing paraneoplastic Cushing syndrome.',
    pearl: 'Small cell lung carcinoma can produce ACTH or ADH as paraneoplastic syndromes.',
    trap: 'Squamous cell lung carcinoma is classically linked to PTHrP-mediated hypercalcemia.',
  }),
  q({
    id: 'qCOVPATONC005',
    subject: 'Pathology',
    system: 'Oncology',
    concept: 'Metastatic spread through lymphatics in carcinoma',
    topic: 'Metastatic Patterns',
    contentArea: 'Multisystem Processes & Disorders',
    angle: 'pathology',
    stem: 'A patient with an invasive breast carcinoma has tumor cells in an axillary sentinel lymph node. Which route of spread is most characteristic for carcinomas?',
    correct: 'Lymphatic invasion with regional lymph node metastasis',
    distractors: ['Pure hematogenous spread without lymph node involvement', 'Direct spread only along peripheral nerves', 'Maternal mitochondrial transmission'],
    explanation: 'The best answer is lymphatic invasion with regional lymph node metastasis because carcinomas commonly spread first through lymphatics to draining nodes.',
    pearl: 'Carcinomas often spread via lymphatics; sarcomas more often spread hematogenously.',
    trap: 'Hematogenous spread can occur in carcinoma, but sentinel lymph node involvement reflects lymphatic spread.',
  }),
]
