/**
 * USMLE Laboratory Reference Values — single source of truth.
 * Ranges match First Aid 2025, UWorld, NBME, and Amboss adult reference standards.
 * Values represent adults unless otherwise noted.
 */
export const USMLE_LAB_REFERENCE = [
  {
    category: 'Hematology',
    tests: [
      { test: 'Hemoglobin, male',        value: '13.5–17.5 g/dL' },
      { test: 'Hemoglobin, female',       value: '12.0–16.0 g/dL' },
      { test: 'Hematocrit, male',         value: '41–53%' },
      { test: 'Hematocrit, female',       value: '36–46%' },
      { test: 'MCV',                      value: '80–100 fL' },
      { test: 'MCH',                      value: '27–33 pg/cell' },
      { test: 'MCHC',                     value: '33–36 g/dL' },
      { test: 'RDW',                      value: '11.5–14.5%' },
      { test: 'Reticulocyte count',       value: '0.5–1.5%' },
      { test: 'WBC',                      value: '4,500–11,000/µL' },
      { test: 'Neutrophils (segs)',        value: '54–62%' },
      { test: 'Band neutrophils',         value: '3–5%' },
      { test: 'Eosinophils',              value: '1–3%' },
      { test: 'Basophils',               value: '0–0.75%' },
      { test: 'Lymphocytes',             value: '25–33%' },
      { test: 'Monocytes',               value: '3–7%' },
      { test: 'Platelet count',          value: '150,000–400,000/µL' },
    ],
  },
  {
    category: 'Coagulation',
    tests: [
      { test: 'PT',              value: '11–15 s' },
      { test: 'aPTT',            value: '25–40 s' },
      { test: 'INR',             value: '0.8–1.2' },
      { test: 'Thrombin time',   value: '< 24 s' },
      { test: 'Bleeding time',   value: '2–7 min' },
      { test: 'Fibrinogen',      value: '200–400 mg/dL' },
      { test: 'D-dimer',         value: '< 0.5 µg/mL' },
    ],
  },
  {
    category: 'Serum Chemistry',
    tests: [
      { test: 'Sodium',            value: '136–145 mEq/L' },
      { test: 'Potassium',         value: '3.5–5.0 mEq/L' },
      { test: 'Chloride',          value: '95–105 mEq/L' },
      { test: 'Bicarbonate',       value: '22–28 mEq/L' },
      { test: 'Anion gap',         value: '8–12 mEq/L' },
      { test: 'BUN',               value: '7–20 mg/dL' },
      { test: 'Creatinine',        value: '0.6–1.2 mg/dL' },
      { test: 'BUN:Creatinine',    value: '10–20:1' },
      { test: 'Glucose (fasting)', value: '70–110 mg/dL' },
      { test: 'Calcium, total',    value: '8.5–10.5 mg/dL' },
      { test: 'Calcium, ionized',  value: '4.5–5.5 mg/dL' },
      { test: 'Magnesium',         value: '1.5–2.5 mEq/L' },
      { test: 'Phosphate',         value: '2.5–4.5 mg/dL' },
      { test: 'Uric acid',         value: '3.5–7.2 mg/dL' },
      { test: 'Serum osmolality',  value: '275–295 mOsm/kg H₂O' },
    ],
  },
  {
    category: 'Liver & GI',
    tests: [
      { test: 'ALT (SGPT)',        value: '7–40 U/L' },
      { test: 'AST (SGOT)',        value: '10–40 U/L' },
      { test: 'Alkaline phosphatase', value: '25–125 U/L' },
      { test: 'GGT',               value: '8–61 U/L' },
      { test: 'Total bilirubin',   value: '0.1–1.0 mg/dL' },
      { test: 'Direct bilirubin',  value: '0.0–0.3 mg/dL' },
      { test: 'Indirect bilirubin', value: '0.1–0.8 mg/dL' },
      { test: 'Albumin',           value: '3.5–5.5 g/dL' },
      { test: 'Total protein',     value: '6.0–8.0 g/dL' },
      { test: 'LDH',               value: '100–190 U/L' },
      { test: 'Amylase',           value: '25–125 U/L' },
      { test: 'Lipase',            value: '10–140 U/L' },
    ],
  },
  {
    category: 'Lipids',
    tests: [
      { test: 'Total cholesterol',  value: '< 200 mg/dL' },
      { test: 'LDL cholesterol',    value: '< 130 mg/dL (optimal < 100)' },
      { test: 'HDL, male',          value: '> 40 mg/dL' },
      { test: 'HDL, female',        value: '> 50 mg/dL' },
      { test: 'Triglycerides',      value: '< 150 mg/dL' },
    ],
  },
  {
    category: 'Thyroid',
    tests: [
      { test: 'TSH',       value: '0.4–4.0 µIU/mL' },
      { test: 'Free T₄',  value: '0.9–2.4 ng/dL' },
      { test: 'Free T₃',  value: '2.3–4.2 pg/mL' },
      { test: 'Total T₄', value: '5.0–12.0 µg/dL' },
      { test: 'Total T₃', value: '80–200 ng/dL' },
    ],
  },
  {
    category: 'Cardiac',
    tests: [
      { test: 'Troponin I',  value: '< 0.04 ng/mL' },
      { test: 'Troponin T',  value: '< 0.01 ng/mL' },
      { test: 'CK-MB',       value: '< 5% of total CK' },
      { test: 'CK, total',   value: '30–170 U/L' },
      { test: 'BNP',         value: '< 100 pg/mL' },
      { test: 'NT-proBNP',   value: '< 125 pg/mL' },
    ],
  },
  {
    category: 'Endocrine',
    tests: [
      { test: 'HbA1c',             value: '< 5.7% normal; < 6.5% DM Dx' },
      { test: 'Cortisol (8 AM)',   value: '5–25 µg/dL' },
      { test: 'ACTH',              value: '9–52 pg/mL' },
      { test: 'Aldosterone',       value: '3–10 ng/dL (upright)' },
      { test: 'PTH',               value: '10–65 pg/mL' },
      { test: 'PTHrP',             value: '< 2 pmol/L' },
      { test: 'Insulin (fasting)', value: '2–20 µIU/mL' },
      { test: 'C-peptide',         value: '0.5–2.0 ng/mL' },
      { test: 'GH (fasting)',      value: '< 5 ng/mL' },
      { test: 'IGF-1 (adult)',     value: '116–358 ng/mL' },
      { test: 'Testosterone, male', value: '300–1000 ng/dL' },
      { test: 'Testosterone, female', value: '15–70 ng/dL' },
      { test: 'LH (follicular)',   value: '1–18 mIU/mL' },
      { test: 'FSH (follicular)',  value: '3–10 mIU/mL' },
      { test: 'Estradiol (follicular)', value: '20–150 pg/mL' },
      { test: 'Prolactin, female', value: '< 20 ng/mL' },
      { test: 'Prolactin, male',   value: '< 15 ng/mL' },
      { test: 'DHEA-S, male',      value: '280–640 µg/dL' },
      { test: 'DHEA-S, female',    value: '65–380 µg/dL' },
    ],
  },
  {
    category: 'Arterial Blood Gas',
    tests: [
      { test: 'pH',          value: '7.35–7.45' },
      { test: 'PaO₂',       value: '75–100 mmHg' },
      { test: 'PaCO₂',      value: '35–45 mmHg' },
      { test: 'HCO₃⁻',      value: '22–28 mEq/L' },
      { test: 'O₂ saturation', value: '95–100%' },
      { test: 'Base excess', value: '−2 to +2 mEq/L' },
    ],
  },
  {
    category: 'Renal & Urine',
    tests: [
      { test: 'Creatinine clearance', value: '75–125 mL/min' },
      { test: 'Urine osmolality',     value: '50–1200 mOsm/kg H₂O' },
      { test: 'Urine sodium',         value: '> 20 mEq/L (euvolemic)' },
      { test: 'FENa',                 value: '< 1% prerenal; > 2% intrinsic' },
      { test: 'Urine specific gravity', value: '1.003–1.030' },
      { test: 'Urine protein',        value: '< 150 mg/24 hr' },
      { test: 'Microalbuminuria',     value: '30–300 mg/24 hr' },
    ],
  },
  {
    category: 'CSF',
    tests: [
      { test: 'Opening pressure', value: '70–180 mmH₂O' },
      { test: 'Glucose',          value: '50–75 mg/dL (> 2/3 serum)' },
      { test: 'Protein',          value: '15–45 mg/dL' },
      { test: 'WBC',              value: '0–5 lymphocytes/µL' },
      { test: 'RBC',              value: '0 cells/µL' },
    ],
  },
  {
    category: 'Iron Studies & Misc',
    tests: [
      { test: 'Iron, serum',         value: '60–160 µg/dL' },
      { test: 'Ferritin, male',      value: '12–300 ng/mL' },
      { test: 'Ferritin, female',    value: '12–150 ng/mL' },
      { test: 'TIBC',                value: '250–370 µg/dL' },
      { test: 'Transferrin sat.',    value: '20–50%' },
      { test: 'Vitamin B12',         value: '200–900 pg/mL' },
      { test: 'Folate',              value: '5–25 ng/mL' },
      { test: 'Erythropoietin',      value: '4–26 mU/mL' },
      { test: 'Haptoglobin',         value: '26–185 mg/dL' },
      { test: 'CRP',                 value: '< 1.0 mg/dL' },
      { test: 'ESR, male',           value: '0–15 mm/hr' },
      { test: 'ESR, female',         value: '0–20 mm/hr' },
      { test: 'Complement C3',       value: '90–180 mg/dL' },
      { test: 'Complement C4',       value: '16–47 mg/dL' },
      { test: 'PSA (< 40 yr)',       value: '< 2.0 ng/mL' },
      { test: 'PSA (40–70 yr)',      value: '< 4.0 ng/mL' },
      { test: 'β-hCG (non-pregnant)', value: '< 5 mIU/mL' },
    ],
  },
]
